### ISSUE TITLE
Allow symfony 5

### ISSUE THREAD

**Issue by Mandzuk** [eMAGTechLabs/RabbitMqBundle#25]
Hello. Can I install the package on the Symfony 5? When I install as composer require php-amqplib/rabbitmq-bundle, I got
`Problem 1
    - php-amqplib/rabbitmq-bundle v1.14.4 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - php-amqplib/rabbitmq-bundle v1.14.3 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - php-amqplib/rabbitmq-bundle v1.14.2 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - php-amqplib/rabbitmq-bundle v1.14.1 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - php-amqplib/rabbitmq-bundle v1.14.0 requires symfony/dependency-injection ^2.7|^3.0|^4.0 -> no matching package found.
    - Installation request for php-amqplib/rabbitmq-bundle ^1.14 -> satisfiable by php-amqplib/rabbitmq-bundle[v1.14.0, v1.14.1, v1.14.2, v1.14.3, v1.14.4].
`

**Comment by mihaileu** [comment]
Hello, @Mandzuk you are still using the old package. 

This is the new package https://packagist.org/packages/emag-tech-labs/rabbitmq-bundle

`composer require emag-tech-labs/rabbitmq-bundle`

**Comment by webdevilopers** [comment]
Works like a charm.

Could you please update the index page too?

* https://github.com/eMAGTechLabs/RabbitMqBundle/issues/25

Thanks in advance.
