### ISSUE TITLE
Unable to get rabbitmq client dependency in controller

### ISSUE THREAD

**Issue by wajdijurry** [eMAGTechLabs/RabbitMqBundle#26]
I tried to follow this example from your documentation:
https://github.com/eMAGTechLabs/RabbitMqBundle#rpc-or-replyresponse

I followed the steps precisely, but when calling controller action, it throws an exception:
```
Service \"old_sound_rabbit_mq.integer_store_rpc\" not found: even though it exists in the app's container, the container inside \"App\\Controller\\StoreController\" is a smaller service locator that only knows about the \"doctrine\", \"http_kernel\", \"parameter_bag\", \"request_stack\", \"router\", \"security.authorization_checker\", \"security.csrf.token_manager\", \"security.token_storage\", \"serializer\" and \"session\" services. Try using dependency injection instead.
```

I tried to use  dependency injection, but it throws another exception:
```
Cannot autowire service "App\Controller\MyController": argument "$client" of method "__construct()" references class "OldSound\RabbitMqBundle\RabbitMq\RpcClient" but no such service exists. You should maybe alias this class to the existing "old_sound_rabbit_mq.integer_store_rpc" service.
```

On both cases, I think it's a bug or the documentation is not clarified well.

Symfony 5.0.7 (env: dev, debug: true)

**Comment by mihaileu** [comment]
@stefanovik could you please take a look, @andreea-anamaria  couldn't reproduce this. Maybe you can. 
Thanks

**Comment by stefanovik** [comment]
@mihaileu I will take a look and come back with what i found

**Comment by stefanovik** [comment]
@wajdijurry I couldn't reproduce this problem. Can you perhaps provide more information? How did you configure the services.yaml? Code samples with service definitions and their usage would be very helpful. 

Thank you,
Stefan

**Comment by mihaileu** [comment]
@wajdijurry do you still have this issue? We will close this in a few days if you cannot give us more information as we didn't reproduced it
