### ISSUE TITLE
PHP8 Compatibility

### ISSUE THREAD

**Issue by jokaorgua** [eMAGTechLabs/RabbitMqBundle#40]
Due to the fact that this bundle is used php-amqplib there is a deprecation message during using the bundle

Example: Required parameter $exchange follows optional parameter $ticket

https://github.com/php-amqplib/php-amqplib/issues/846 - here we can see that php8 support will be not soon and the author does not recommend to use it with php8 at all

Any ideas where to switch for php8 support and how long to wait until this bundle will support php8 without deprecation messages?

**Comment by andreea-anamaria** [comment]
After this PR: https://github.com/php-amqplib/php-amqplib/pull/854 will be merged we will try to make eMAGTechLabs/RabbitMqBundle compatible with PHP8.

**Comment by Majkl578** [comment]
@andreea-anamaria Any update? That referenced PR has been closed as invalid.

**Comment by andreea-anamaria** [comment]
Based on this comment: https://github.com/php-amqplib/php-amqplib/pull/854#issuecomment-748274017 seems like that deprecation message will be fixed in a major version.

**Comment by steffenbrand** [comment]
I cannot even upgrade:

> emag-tech-labs/rabbitmq-bundle 2.4.0 requires php ^7.1 -> your php version (8.0.1) does not satisfy that requirement.

If it's only deprecation messages, maybe you can update the version constraint anyways?

**Comment by mihaileu** [comment]
PHP8 compatibility was merged into amqplib library: https://github.com/php-amqplib/php-amqplib/pull/858

@andreea-anamaria could you please take a look
